### ISSUE TITLE
Unable to use Pi-hole's built in DHCP server

### ISSUE THREAD

**Issue by testphreak** [mjtechguy/terransible-wirehole#11]
Hi @mjtechguy, first of, thank you for creating this amazing project! It really does a nice job of automating the deployment and management of the stack via Terraform and Ansible. The documentation was easy to follow as well. I was able to successfully set up the stack on AWS. 

With Pi-hole, you can have the devices on your network use Pi-hole's DNS server by setting it either at the router or via the Admin interface at http://pi.hole/admin/settings.php?tab=piholedhcp. This helps with network level ad blocking to devices such as smart TVs, IOTs etc. Currently I don't think the documentation in this project shows how to do this.

I tried following the official documentation for how that can be achieved, but somehow I can't get it to work -
1. https://discourse.pi-hole.net/t/how-do-i-use-pi-holes-built-in-dhcp-server-and-why-would-i-want-to/3026
2. https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245

Here's the screenshot from my Admin UI -
![image](https://user-images.githubusercontent.com/10567800/102863251-29a33400-43e7-11eb-89ed-d2477ff3900e.png)

I made sure to disable DHCP on my router before enabling DHCP via the Admin UI. I also restarted both my router and device multiple times to renew the DHCP lease, but I can't get it to work.

Any advice on how I can use Pi-hole's DHCP server to hand out IP addresses to the devices on my network?

**Comment by mjtechguy** [comment]
Awesome to hear @testphreak. Glad you are enjoying using the solution.

I believe this an AWS or maybe overall cloud provider issue. They are likely not going to allow broadcast traffic like DHCP to run on their network. 

Just to make sure I understand, you are running Pihole in AWS and want you local machine to get a DHCP lease from your Pihole server running in AWS?

MJ

**Comment by testphreak** [comment]
Hi @mjtechguy, yeah I was trying to get a DHCP lease from the Pi-hole server in AWS. I am trying to understand the technical limitations of such a solution.

Based on the Pi-hole [documentation](https://docs.pi-hole.net/docker/DHCP/), it appears that it should be possible to have Pi-hole hand out IP addresses to devices on my local network, ideally with networking mode `macvlan`. The networking mode in this project appears to be using the [default](https://github.com/mjtechguy/terransible-wirehole/blob/master/ansible/files/docker-compose.yml#L4-L9) `bridge` network.

There is a linked [example](http://tonylawrence.com/posts/unix/synology/free-your-synology-ports/) in the documentation, to achieve DHCP capabilities, but it seems to be for a local server setup as opposed to one hosted in the cloud.

**Comment by mjtechguy** [comment]
Yes, this would work on your home network. But I think AWS may block DHCP broadcast traffic. 

Remote DHCP is not recommended. You should probably get another Pihole on you local network, maybe on a Raspberry Pi.

You will also run into an issue where the traffic on your local network would need to know the path to the AWS network across your local Wireguard endpoint to your AWS deployment. This is more of a site to site setup and much more complex.

MJ

**Comment by testphreak** [comment]
Thanks for the explanation. I agree that having a second Pi-hole on my local network is the way to go. 

Unrelated, but it's been pretty neat learning about Wireguard, Pi-hole and Unbound. I was trying to understand why Wireguard was needed at all. Then I read that a public facing DNS server could be part of DDOS attacks. Hence putting the instance behind a VPN makes sense.
