### ISSUE TITLE
Permission issue on "id_rsa"

### ISSUE THREAD

**Issue by alexsorel** [mjtechguy/terransible-wirehole#14]
At step 8 of the OCI deployment, when running "ansible oci -m ping" I'm getting the following outcome:

`ubuntu@instance-boot:~/terransible-wirehole/ansible$ ansible oci -m ping
[WARNING]: Unhandled error in Python interpreter discovery for host 158.101.118.196: Failed to connect to the
host via ssh: Warning: Permanently added '158.101.118.196' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @         WARNING: UNPROTECTED PRIVATE KEY FILE!
@  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Permissions 0775 for
'/home/ubuntu/.ssh/id_rsa' are too open.  It is required that your private key files are NOT accessible by
others.  This private key will be ignored.  Load key "/home/ubuntu/.ssh/id_rsa": bad permissions
ubuntu@158.101.118.196: Permission denied (publickey).
158.101.118.196 | UNREACHABLE! => {
    "changed": false,
    "msg": "Data could not be sent to remote host \"158.101.118.196\". Make sure this host can be reached over ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nPermissions 0775 for '/home/ubuntu/.ssh/id_rsa' are too open.\r\nIt is required that your private key files are NOT accessible by others.\r\nThis private key will be ignored.\r\nLoad key \"/home/ubuntu/.ssh/id_rsa\": bad permissions\r\nubuntu@158.101.118.196: Permission denied (publickey).\r\n",
    "unreachable": true
}`

I've tried different permission on the directory "id_rsa" like 0444 or 0440, but with no success.
Can you help me on that?

**Comment by mjtechguy** [comment]
Hi @alexsorel, Please try 0600 on the permissions. The permissions should be only available to your user and to no others.

Let me know if that works.

MJ

**Comment by alexsorel** [comment]
Unfortunately I'm not going through. I've tried permission 0600, and also 0400, on the directory id_rsa with no success. I also tried to set the same permissions on the directory AND the key file located in the directory, no better. Am I correct in the understanding that "id_rsa" is a directory, in which I put the file of my private key? (a file named "ssh-key-ubuntu.key").
I've tried both from an Ubuntu and a CentOS machine, no difference. Thanks a lot for your help and very sorry to bother with permissions but I really don't see how to solve it by myself.

**Comment by mjtechguy** [comment]
Hi @alexsorel. id_rsa is the key name, not the folder name. 

The name of that key can be whatever you like (as you indicated, yours is "ssh-key-ubuntu.key"), but for the sake of this example, lets just stick with id_rsa. You would generate a new key and it would output 2 files. "id_rsa" and "id_rsa.pub". 

The id_rsa.pub is what you load into your cloud provider to access your instances and id_rsa is the private key file you need to set the local path to and make sure permissions are 0600.

Hope that helps.

MJ

**Comment by alexsorel** [comment]
Thank you so much, you made my day! I was definitely not understanding properly, my own fault. Now I have wirehole working like a charm. I will probably if you don't mind fork from you instructions a wiki for newbies like me, so that they avoid mistakes like I did and some others I did before as well. Thanks again for your support, great job done here. Alex.

**Comment by mjtechguy** [comment]
Good to hear @alexsorel. Glad it is working for you.

Yes, please create a guide an feel free to submit it as a PR or on your own repo. Sharing of knowledge and tools is what is most important here!

MJ
