### ISSUE TITLE
could not find proper configuration file

### ISSUE THREAD

**Issue by yfhyou** [mjtechguy/terransible-wirehole#6]
error when running `terraform plan`

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.oci_identity_availability_domain.ad: Refreshing state...

Error: did not find a proper configuration for private key

  on main.tf line 138, in data "oci_identity_availability_domain" "ad":
 138: data "oci_identity_availability_domain" "ad" {
```

**Comment by mjtechguy** [comment]
This appears to be an error with using a relative path for the `oracle_api_private_key_path` in the terraform.tfvars file.

Please provide the full path to the .pem file and try again.

I have updated the .sample file to make a note of that, so you should see that if you pull the latest.

MJ

**Comment by yfhyou** [comment]
I guess I'm a bit confused what file I'm putting here.  I don't have a .pem file in my .ssh directory, only a file called authorized_keys. That file has my private key, but give me the same error when I reference it.
I did create a file oci_api_key.pem in the .oci directory when following the oracle instructions. Is that the one I should reference?

EDIT: tried linking to that file /home/ubuntu/.oci/oci_api_key.pem and got the same error

**Comment by hyber-code** [comment]
i am also getting the same error

**Comment by mjtechguy** [comment]
I am investigating this today. I will let you know what I find.

MJ

**Comment by yfhyou** [comment]
Any luck with this issue?

**Comment by hyber-code** [comment]
i think I solved the issue by moving the files from ~/xyz to /home/xyz, i read somewhere but do not remember the source, infact i  moved the whole terraform directory from ~/xyz to /home/xyz. hope it helps you, update here if it works.

**Comment by hyber-code** [comment]
There can be multiple reasons for this like:

Not specifying either a private_key or private_key_path in the config
Specifying a private_key_path that's not a valid path to a private key file
Not specifying a private_key_password for a private key that's encrypted
Specifying an incorrect private_key_password for an encrypted private key

i found possible reasons from another repo's issue list
```
https://github.com/terraform-providers/terraform-provider-oci/issues/1217#issuecomment-714605595
```

**Comment by hyber-code** [comment]
> I guess I'm a bit confused what file I'm putting here. I don't have a .pem file in my .ssh directory, only a file called authorized_keys. That file has my private key, but give me the same error when I reference it.
> I did create a file oci_api_key.pem in the .oci directory when following the oracle instructions. Is that the one I should reference?
> 
> EDIT: tried linking to that file /home/ubuntu/.oci/oci_api_key.pem and got the same error

copy the key to same folder as terraform

**Comment by mjtechguy** [comment]
@hyber-code you are correct.

I am not sure why it worked for me in my .ssh directory before. Now I cannot get it to recognize the .pem file there.

There is a .pem exclusion in the .gitignore file, so placing it in the same directory as the oracle terraform should be fine.

Thanks for the research @hyber-code. @youngt2  please test with that.

MJ

**Comment by mjtechguy** [comment]
Closing as I confirm that the location of the OCI .pem appears to be the issue.

**Comment by yfhyou** [comment]
Yup! Worked for me as well. Thanks.
